@startuml
left to right direction

actor "Formateur" as F
actor "Surveillant Général" as SG

rectangle "Saisie d'Absence Sprint 2" {
    usecase UC1 as "Consulter Liste des Absences"
    usecase UC2 as "Filtrer les Absences"
    usecase UC3 as "Rechercher Absence par Classe"
}

F -- UC1 
SG -- UC2 
SG -- UC3 

@enduml
