@startuml
left to right direction
actor "Surveillant Général" as SG

rectangle "Saisie d'Absence Sprint 1" {
    usecase UC2 as "Visualiser Statistiques d'Absence"
    usecase UC3 as "Consulter Absences du Jour"
    usecase UC4 as "Visualiser Élèves Absents"
    usecase UC5 as "Visualiser Total Hebdomadaire"
    usecase UC6 as "Visualiser Séances Non Traitées"
    usecase UC7 as "Exporter les Données"

    UC2 <.. UC3 : <<extend>>
    UC2 <.. UC4 : <<extend>>
    UC2 <.. UC5 : <<extend>>
    UC2 <.. UC6 : <<extend>>
    UC2 <.. UC7 : <<extend>>
}

SG -- UC2 

@enduml
