@startuml
left to right direction

actor "Surveillant Général" as SG

rectangle "Saisie d'Absence Sprint 3" {
    usecase UC1 as "Générer Rapport d'Absence"
    usecase UC2 as "Rechercher Absence par Apprenant"
}

SG -- UC1 
SG -- UC2 

@enduml
